import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import ThemeProvider from "./components/ThemeProvider";
import FinanceProvider from "./contexts/FinanceContex";
import AddExpense from "./components/AddExpense";
import AddIncome from "./components/AddIncome";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Finance Tracker App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} transition-color duration-500 flex flex-col min-h-screen antialiased bg-white dark:bg-black text-black dark:text-white`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <FinanceProvider>
              <Header />
              <main className="flex-1">{children}</main>
              <AddExpense/>
              <AddIncome/>
            </FinanceProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
