import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./components/Header";
import ThemeProvider from "./components/ThemeProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Finance Tracker App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} transition-color duration-500 flex flex-col min-h-screen antialiased bg-white dark:bg-black text-black dark:text-white`}
        >
          <ClerkProvider>
            <Header />
            <main className="flex-1">{children}</main>
          </ClerkProvider>
        </body>
      </html>
    </ThemeProvider>
  );
}
